name: Deploy Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deta, deploy
        run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh
          deta deploy
